Repository CS305-F18-TeamDOS/Gradebook, pull requests merged in 2018-11, with the labels that each got.

#7 Schema consistency update
  src/db/addAssessmentItemMgmt.sql
  src/db/createTables.sql
  src/db/dropTables.sql
Labels: enhancement

#8 Update createTables.sql
  src/db/createTables.sql
Labels: one review

#13 Add new before login ui
  src/webapp/client/html/README.md
  src/webapp/client/html/about.html
  src/webapp/client/html/changeLog.html
  src/webapp/client/html/login.html
  src/webapp/client/js/index.js
Labels: full review

#12 Create assessment management
  src/db/addAssessmentComponentMgmt.sql
  src/db/addAssessmentItemMgmt.sql
  src/db/addSubmissionMgmt.sql
Labels: full review

#17 Add db mgmt functionality
  src/db/addAssessmentComponentMgmt.sql
  src/db/addAssessmentItemMgmt.sql
  src/db/addAttendanceMgmt.sql
  src/db/addInstructorMgmt.sql
  src/db/addReferenceData.sql
  src/db/addSeasonMgmt.sql
  src/db/addSectionMgmt.sql
  src/db/addSubmissionMgmt.sql
  src/db/addTableConstraintFunctions.sql
  src/db/createTables.sql
  src/db/humanizeStudentData.sql
  src/db/importCourseSchedule/prepareCourseScheduleImport.sql
  src/db/importRoster/prepareRosterImport.sql
Labels: enhancement, full review

#21 Add assessment api
  src/webapp/client/index.html
  src/webapp/client/js/index.js
  src/webapp/gradebookServer.js
  src/webapp/node_modules/buffer-writer/.travis.yml
  src/webapp/node_modules/buffer-writer/index.js
  src/webapp/node_modules/buffer-writer/package.json
  src/webapp/node_modules/buffer-writer/test/writer-tests.js
  src/webapp/node_modules/pg-pool/.travis.yml
  src/webapp/node_modules/pg-pool/index.js
  src/webapp/node_modules/pg-pool/package.json
  src/webapp/node_modules/pg-pool/test/connection-timeout.js
  src/webapp/node_modules/pg-pool/test/sizing.js
  src/webapp/node_modules/pg/package.json
  src/webapp/node_modules/sjcl/.travis.yml
  src/webapp/node_modules/sjcl/bower.json
  src/webapp/node_modules/sjcl/core/bn.js
  src/webapp/node_modules/sjcl/core/codecArrayBuffer.js
  src/webapp/node_modules/sjcl/core/convenience.js
  src/webapp/node_modules/sjcl/package.json
  src/webapp/node_modules/sjcl/test/bn_test.js
  src/webapp/node_modules/sjcl/test/ccm_vectors.js
  src/webapp/node_modules/sjcl/test/ecc_test.js
  src/webapp/node_modules/sjcl/test/ecc_vectors.js
  src/webapp/package-lock.json
  src/webapp/package.json
  tests/data/Attendance/importAttendance.psql
  tests/data/InstructorEmail/addEmailByInstructorID.sql
  tests/data/InstructorEmail/addEmailByInstructorName.sql
  tests/humanizeStudentData/addTestData.sql
  tests/humanizeStudentData/testResults.sql
Labels: full review

#23 Add assessment Mgmt. UI
  src/webapp/client/html/README.md
  src/webapp/client/html/changeLog.html
  src/webapp/client/html/manageAssessmentTypesForm.html
  src/webapp/client/html/manageAssessments.html
  src/webapp/gradebookServer.js
Labels: enhancement, one review
